### ISSUE TITLE
samples libk omitted and olther news2news examples

### ISSUE THREAD

**Issue by ybenameur** [VFPX/Win32API#1]
1-https://github.com/VFPX/Win32API/blob/master/samples/sample_577.md
 Displaying Windows shell folders in TreeView control with Visual FoxPro FLL
this url dont exist and dont listed in samples.
Please verify also samples 586,509,510,525,,583,..... forget ?

2-examples seen in news2news as 
     -dialogs/messageboxes,menus,....i see them in old news2news (site down)
not integrated in this vfpx win32api ?

**Comment by tbleken** [comment]
This will hopefully be fixed within the next week.
