### ISSUE TITLE
"Download MsgBox FLL" does not work

### ISSUE THREAD

**Issue by Mike-SP** [VFPX/Win32API#2]
There are many links to "Download MsgBox FLL" (e.g. http://www.news2news.com/vfp/?solution=3) that fail with:

Forbidden
You don't have permission to access /vfp/ on this server.
Server unable to read htaccess file, denying access to be safe

Apache Server at www.news2news.com Port 80

**Comment by tbleken** [comment]
I am busy correcting all bad links, and adding the missing material. This will hopefully be fixed within the next week.

**Comment by rikaye** [comment]
Hi Tore,

It was nice to meet you at SWFox. As Tuvia mentioned this FLL in his modern UI presentation I thought I would go hunt it down but it's not here. Any chance of recovering this particular part of the news2 news content? The link to the sample code also returns a 404. https://github.com/VFPX/Win32API/blob/master/samples/sample_424.md

Of course, if the original author does not want the FLL out there then it would be good to know that so we can look at other alternatives for a messagebox replacement.

Thanks.

**Comment by tbleken** [comment]
Some of the samples which were available at News2news.com are not presently available here since they depend on custom made libraries. Some of these samples may be added later, if the necessary libraries are released to the public.
