### ISSUE TITLE
Windows Compression API

### ISSUE THREAD

**Issue by dcipher** [VFPX/Win32API#8]
Hi

Are there any examples of using the builtin Windows API from creating zip files?

Simon

**Comment by devicecontext** [comment]
Hi Simon,

There is no such example. No plans to have one – the library of APIs is no longer maintained by me.

Thanks
AM

From: dcipher ***@***.***>
Sent: Thursday, December 21, 2023 9:37 AM
To: VFPX/Win32API ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VFPX/Win32API] Windows Compression API (Issue #8)


Hi

Are there any examples of using the builtin Windows API from creating zip files?

Simon

**Comment by tbleken** [comment]
What about sample 568 at https://github.com/VFPX/Win32API/blob/master/samples/sample_568.md?
